---
swagger: "2.0"
info:
  description: "Dis the server"
  version: "1.0.0"
  title: "Swagbot API"
host: "localhost:8000"
basePath: "/api"
tags:
- name: "user"
  description: ""
- name: "room"
  description: ""
- name: "message"
  description: ""
schemes:
- "https"
- "http"
paths:
  /users:
    get:
      tags:
      - "user"
      summary: "Get all users"
      description: ""
      operationId: "get_all_users"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Users successfully retrieved"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    post:
      tags:
      - "user"
      summary: "Creates a new user"
      description: ""
      operationId: "add_user"
      parameters:
      - in: "body"
        name: "body"
        description: "User must provide a name"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "User successfully created"
        "405":
          description: "Invalid input"
        "409":
          description: "User already exists"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/{id}:
    get:
      tags:
      - "user"
      summary: "Get user from id"
      description: ""
      operationId: "get_user_from_id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The id for the name needed"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Users successfully retrieved from id"
        "400":
          description: "Could not get user from id"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    delete:
      tags:
      - "user"
      summary: "Delete user from id"
      description: ""
      operationId: "delete_user_from_id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The id for the name needed"
        required: true
        type: "string"
      responses:
        "200":
          description: "Users successfully deletetd"
        "400":
          description: "Could not delete user from id"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
