# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.room import Room
from swagger_server.models.user_messages import UserMessages

from swagger_server import util


class RoomMessages(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, room: Room=None, messages: List[UserMessages]=None):  # noqa: E501
        """RoomMessages - a model defined in Swagger

        :param room: The room of this RoomMessages.  # noqa: E501
        :type room: Room
        :param messages: The messages of this RoomMessages.  # noqa: E501
        :type messages: List[UserMessages]
        """
        self.swagger_types = {
            'room': Room,
            'messages': List[UserMessages]
        }

        self.attribute_map = {
            'room': 'room',
            'messages': 'Messages'
        }

        self._room = room
        self._messages = messages

    @classmethod
    def from_dict(cls, dikt) -> 'RoomMessages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoomMessages of this RoomMessages.  # noqa: E501
        :rtype: RoomMessages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def room(self) -> Room:
        """Gets the room of this RoomMessages.


        :return: The room of this RoomMessages.
        :rtype: Room
        """
        return self._room

    @room.setter
    def room(self, room: Room):
        """Sets the room of this RoomMessages.


        :param room: The room of this RoomMessages.
        :type room: Room
        """

        self._room = room

    @property
    def messages(self) -> List[UserMessages]:
        """Gets the messages of this RoomMessages.


        :return: The messages of this RoomMessages.
        :rtype: List[UserMessages]
        """
        return self._messages

    @messages.setter
    def messages(self, messages: List[UserMessages]):
        """Sets the messages of this RoomMessages.


        :param messages: The messages of this RoomMessages.
        :type messages: List[UserMessages]
        """

        self._messages = messages
